"""create_initial_tables

Revision ID: 5ce78c13bfc6
Revises: 
Create Date: 2026-09-07 19:11:19.268780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry, alembic_helpers


# revision identifiers, used by Alembic.
revision: str = '5ce78c13bfc6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drive_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drive_sessions_started_at'), 'drive_sessions', ['started_at'], unique=False)
    op.create_index(op.f('ix_drive_sessions_status'), 'drive_sessions', ['status'], unique=False)
    op.create_geospatial_table('road_networks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('region', sa.String(length=128), nullable=False),
    sa.Column('road_segments', sa.JSON(), nullable=False),
    sa.Column('geom', Geometry(geometry_type='MULTILINESTRING', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_road_networks_geom', 'road_networks', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_road_networks_region'), 'road_networks', ['region'], unique=False)
    op.create_geospatial_table('telemetry_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('heading', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('gnss_available', sa.Boolean(), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['drive_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_telemetry_records_geom', 'telemetry_records', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_telemetry_records_session_id'), 'telemetry_records', ['session_id'], unique=False)
    op.create_index('ix_telemetry_records_session_id_timestamp', 'telemetry_records', ['session_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_telemetry_records_timestamp'), 'telemetry_records', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_records_timestamp'), table_name='telemetry_records')
    op.drop_index('ix_telemetry_records_session_id_timestamp', table_name='telemetry_records')
    op.drop_index(op.f('ix_telemetry_records_session_id'), table_name='telemetry_records')
    op.drop_geospatial_index('idx_telemetry_records_geom', table_name='telemetry_records', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('telemetry_records')
    op.drop_index(op.f('ix_road_networks_region'), table_name='road_networks')
    op.drop_geospatial_index('idx_road_networks_geom', table_name='road_networks', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('road_networks')
    op.drop_index(op.f('ix_drive_sessions_status'), table_name='drive_sessions')
    op.drop_index(op.f('ix_drive_sessions_started_at'), table_name='drive_sessions')
    op.drop_table('drive_sessions')
    # ### end Alembic commands ###
